export default {
  "META.description": `딥러닝 머신비전 솔루션 프로바이더. 기계 대신 사람이 하던 일을 자동화함으로써 세상에 기여할 수 있다고 믿습니다.`,

  "NAVBAR.product.support": `Product Inquiry`,
  "NAVBAR.career.philosophy": `Philosophy of Personnel`,
  "NAVBAR.career.recruit": `Hiring Process`,
  "NAVBAR.career.open_position": `Open Positions`,

  "FOOTER.sualabInfo": `Business Registration Number: 220-88-55558  |  CEO: Kiyoung Song\nAddress: Seoul National University Research Park 511, Gwanak-ro 1, Gwanak-gu, Seoul\nGeneral Inquiry: 02-6264-0366 | Sales Inquiry: 02-6264-0362\nCopyright ⓒSualab. All Rights Reserved.`,
  "FOOTER.privateTerms": `Privacy Policy`,

  "MAIN.FIRST.subTitle": `SUALAB believes that artificial intelligence can contribute to the world\nby automating tasks that have required human effort.`,
  "MAIN.SECOND.awardContent_1": `2017 Innovators Awards’\nPLATINUM-level Honoree`,
  "MAIN.SECOND.awardContent_2": `2017 KGCCI Innovation Award’s Winner\nin the Digitalization Innovation Category`,
  "MAIN.SECOND.awardContent_3": `Selected as a ‘2016 Global Top 8 Start-up’\nin the Machine Vision Category`,
  "MAIN.THIRD.bigTitle": `Clients`,
  "MAIN.THIRD.content": `SUALAB has been recognized for its technology and provides solutions\nto world-famous manufacturing companies in various industries.`,
  "MAIN.FOURTH.bigTitle": `Blog`,
  "MAIN.FOURTH.subTitle": `Would you like to learn more about SUALAB’s research fields, such as deep learning and machine vision?`,
  "MAIN.FOURTH.blogBtn": `SUALAB’s Technology Blog`,
  "MAIN.FIFTH.bigTitle": `Recent News`,

  "ABOUT.FIRST.title": `SUALAB contributes to the world by providing a *deep learning inspection solution*\nthat specializes in *machine vision*`,
  "ABOUT.SECOND.missionSubContent": `To contribute to the world by providing its employees with fair\ncompensation for their efforts and work that is worthwhile, and by\nenabling people to become free from tasks that machines can take on`,
  "ABOUT.SECOND.visionSubContent": `Global No.1 in deep learning-based Vision Inspection`,
  "ABOUT.THIRD.title": `A Global Leader in *Deep Learning Machine Vision Solution*`,
  "ABOUT.THIRD.content": `SUALAB is an artificial intelligence-based provider of Deep Learning Machine Vision Solutions.\n\nSUALAB, home of excellent engineers from deep learning and machinery fields, combines the technologies of those industries to fuel research into various technologies and products that make human life more convenient.\n\nIn particular, SUALAB enables inspection of the manufacturing industry by researching various machine vision systems that can replace the human eye in the industrial field based on deep learning, machine vision and super computing technologies.`,
  "ABOUT.FOURTH.subContent": `SUALAB, by using artificial intelligence image analysis technology, provides unmanned\ninspection automation solutions for the display, solar, PCB, film, semiconductor and\nother fields that are difficult to test with existing machine vision technology.`,
  "ABOUT.FOURTH.itemContent_1": `For optimized deep learning training, image pre-processing is performed using various techniques such as machine vision algorithms.`,
  "ABOUT.FOURTH.itemContent_2": `Real-time analysis is conducted based on SUALAB-dedicated learning networks and GPU computing technology.`,
  "ABOUT.FOURTH.itemContent_3": `The solution provides S/W that can generate inspection reports, turn test results into databases, and mark defective areas.`,

  "PEOPLE.title": `SUALAB works with the *best colleagues*`,
  "PEOPLE.c-level": `Management`,
  "PEOPLE.laboratory": `Research Lab`,
  "PEOPLE.business": `Sales Team`,
  "PEOPLE.manage": `Management Support Team`,

  "SUAKIT.title": `SuaKIT, *front-runner in deep learning*, expands the spectrum of *machine vision inspection*`,
  "SUAKIT.FIRST.content": `SuaKIT is a deep learning machine vision inspection software that can be used in various manufacturing fields such as display, solar, PCB, film, and semiconductor.`,
  "SUAKIT.FIRST.subTitle_1": `SuaKIT Training Methods`,
  "SUAKIT.FIRST.subTitle_2": `SuaKIT Core Functions`,
  "SUAKIT.FIRST.methodContent_1": `Train and inspect features of each image`,
  "SUAKIT.FIRST.methodContent_2": `Train and inspect defects by focusing on the differences between two images`,
  "SUAKIT.FIRST.methodContent_3": `Train and inspect defects by analyzing the correlations among various images`,
  "SUAKIT.FIRST.methodContent_4": `Inspect defects by training only normal images (Without defect images)`,
  "SUAKIT.FIRST.cardContent_1": `Inspect defect areas by analyzing various defects on the products.`,
  "SUAKIT.FIRST.cardContent_2": `Classify images and categorize them into defect types or OK/NG groups.`,
  "SUAKIT.FIRST.cardContent_3": `Detect each target object in an image by class.`,
  "SUAKIT.FIRST.useCase_1": `Use cases :  Solar panels, Display, and etc.`,
  "SUAKIT.FIRST.useCase_2": `Use cases :  PCB, Camera module, Film and etc.`,
  "SUAKIT.FIRST.useCase_3": `Use cases :  Pharmaceutical, Food & Beverage, and etc.`,
  "SUAKIT.SECOND.subTitle": `Applicable Industries`,
  "SUAKIT.SECOND.display": `Display`,
  "SUAKIT.SECOND.conduct": `Semiconductor`,
  "SUAKIT.SECOND.sunlight": `Solar`,
  "SUAKIT.SECOND.film": `Film`,
  "SUAKIT.SECOND.etcContent": `Also applicable to other various manufacturing fields,\nsuch as automobile parts, and electrical / electronic products.`,
  "SUAKIT.THIRD.subTitle": `Existing  Machine Vision Inspection vs SuaKIT`,
  "SUAKIT.THIRD.subContent": `With SuaKIT’s deep learning algorithms, the limitations of traditional machine vision inspection methods can be overcome.`,
  "SUAKIT.THIRD.headItem": `Existing Machine Vision Inspection`,
  "SUAKIT.THIRD.itemTitle_1": `Unable to interpret irregular images`,
  "SUAKIT.THIRD.itemContent_1": `In the  case the image is irregular, it is difficult to manually set the values of the defective features. There are many areas that still depend on human visual inspection.`,
  "SUAKIT.THIRD.itemTitle_2": `High-resolution image analysis based on deep learning`,
  "SUAKIT.THIRD.itemContent_2": `SuaKIT can automatically learn and analyze defective feature values ​​through deep learning algorithms, regardless of image complexity.`,
  "SUAKIT.THIRD.itemTitle_3": `Low accuracy`,
  "SUAKIT.THIRD.itemContent_3": `Using existing machine vision inspection, once the characteristic value of the defect has been set, it cannot be changed until the next reference setting, which means the test is vulnerable to even slight deformations and as such accuracy is compromised further, in the case of visual inspection, the test depends on each individual's eyes, which means there may not be a single standard.`,
  "SUAKIT.THIRD.itemTitle_4": `High accuracy`,
  "SUAKIT.THIRD.itemContent_4": `By adopting deep learning algorithms, we not only can respond flexibly to product changes, but also can improve the accuracy of inspection significantly by using manufacturing-specific algorithms and methodologies based on various delivery records in the manufacturing field.`,
  "SUAKIT.THIRD.itemTitle_5": `Excessive optimization costs`,
  "SUAKIT.THIRD.itemContent_5": `Various product types and frequent changes in models often result in excessive  programming costs for optimization.`,
  "SUAKIT.THIRD.itemTitle_6": `Auto optimization  based on deep learning`,
  "SUAKIT.THIRD.itemContent_6": `With pictures of the different types of defects, not only can users easily optimize the program automatically, but they can also further study the images acquired after the line application.`,
  "SUAKIT.FOURTH.itemTitle_1": `Improved Inspection Accuracy`,
  "SUAKIT.FOURTH.itemContent_1": `Deep  learning-based algorithms provide higher inspection accuracy than that found in visual inspection and conventional machine vision inspection.`,
  "SUAKIT.FOURTH.itemTitle_2": `Efficient Human Resources Operations`,
  "SUAKIT.FOURTH.itemContent_2": `With our high-accuracy automated inspection capacity, it is possible for one person to manage more than one inspection equipment.`,
  "SUAKIT.FOURTH.itemTitle_3": `Reduced Optimization Costs`,
  "SUAKIT.FOURTH.itemContent_3": `The learning process is quick and easy, which helps shorten the algorithm optimization process. Additional learning is possible with the images acquired following line application, which reduces optimization costs.`,
  "SUAKIT.FOURTH.itemTitle_4": `Maximized Processing Speed`,
  "SUAKIT.FOURTH.itemContent_4": `By using GPU-processing languages, such as CUDA and cuDNN, we have implemented deep learning algorithms and supported Multi-GPU and Multi-Threading, ultimately maximizing the image processing speed.`,
  "SUAKIT.FOURTH.itemTitle_5": `High Compatibility`,
  "SUAKIT.FOURTH.itemContent_5": `With C ++ and C # APIs, you can replace the existing algorithms in the same language only by changing the checking algorithm.`,
  "SUAKIT.FOURTH.itemTitle_6": `User-Friendly UI`,
  "SUAKIT.FOURTH.itemContent_6": `By providing the best UX based on intuitive UI, we have maximized user convenience.\nEven individuals who are not deep learning experts can easily carry out all inspection processes from labeling to outputting results.`,
  "SUAKIT.FIFTH.question_1": `How many pieces of image data should I train with?`,
  "SUAKIT.FIFTH.answer_1": `This will vary depending on the complexity of the image, but basically 100 images per each defect type are required.`,
  "SUAKIT.FIFTH.question_2": `How much time is required for network learning?`,
  "SUAKIT.FIFTH.answer_2": `This will vary depending on the number of images to be learned, but it takes about 20 minutes for 1,000 images in the dimensions of 1024*1024.`,
  "SUAKIT.FIFTH.question_3": `What is the speed at which image data is processed on the inspection line?`,
  "SUAKIT.FIFTH.answer_3": `Based on Segmentation / Geforce GTX-1080Ti and for image size 1024*1024, the processing speed in real time comes out to about 20 images per second.`,
  "SUAKIT.FIFTH.question_4": `Are there training and/or seminars on using SuaKIT?`,
  "SUAKIT.FIFTH.answer_4": `Upon product inquiry, we will visit your site and go through how to use SuaKIT. Official tutorials will begin upon SuaKIT rental or purchase. `,
  "SUAKIT.FIFTH.question_5": `Is SuaKIT compatible with existing inspection algorithms? If so, how does it work?`,
  "SUAKIT.FIFTH.answer_5": `SuaKIT provides C ++ and C # APIs. If the existing inspection algorithm is developed in C ++ or C #, it can be easily linked through the API.`,
  "SUAKIT.FIFTH.question_6": `Is there a demo version of SuaKIT?`,
  "SUAKIT.FIFTH.answer_6": `No. But SuaKIT rental is available for 20 business days and can be extended once with an additional contract. `,
  "SUAKIT.SIXTH.subTitle": "SuaKIT Brochure",

  "HOWTO.title": `*Anyone* can easily create a *deep learning model* and apply it to *manufacturing sites*`,
  "HOWTO.USAGE.subTitle": `SuaKIT Usage Process`,
  "HOWTO.USAGE.content": `With SuaKIT's intuitive UI, anyone can easily create and test deep learning models.`,
  "HOWTO.USAGE.segmentation.title_1": `01. Image Loading`,
  "HOWTO.USAGE.segmentation.content_1": `Load normal and defective images for training / test. `,
  "HOWTO.USAGE.segmentation.title_2": `02. Image Classification`,
  "HOWTO.USAGE.segmentation.content_2": `Categorize the images into these groups: Train / Validation / Test`,
  "HOWTO.USAGE.segmentation.title_3": `03. Labeling`,
  "HOWTO.USAGE.segmentation.content_3": `Label defective areas of the image according to each defect type.`,
  "HOWTO.USAGE.segmentation.title_4": `04. Model Creation`,
  "HOWTO.USAGE.segmentation.content_4": `Analyze the labeled images to generate a deep learning model.`,
  "HOWTO.USAGE.segmentation.title_5": `05. Test`,
  "HOWTO.USAGE.segmentation.content_5": `Verify the defective areas that were detected by the model.`,
  "HOWTO.USAGE.segmentation.title_6": `06. Export Model`,
  "HOWTO.USAGE.segmentation.content_6": `Export the generated model and use it in conjunction with existing C ++ / C # software.`,
  "HOWTO.USAGE.classification.content_3": `Label images according to product / defect type.`,
  "HOWTO.USAGE.detection.content_3": `Label the defects found on the images in boxes according to type.`,
  "HOWTO.USAGE.classification.content_5": `Verify the images that were classified by type.`,
  "HOWTO.USAGE.detection.content_5": `Test and confirm the product / defect areas detected by the model.`,
  "HOWTO.APPLY.subTitle": `SuaKIT Application Process`,
  "HOWTO.APPLY.content": `You can apply SuaKIT in the following procedures:`,
  "HOWTO.APPLY.itemTitle_1": `Image Acquisition`,
  "HOWTO.APPLY.itemContent_1": `Acquire images through existing machine  vision equipments.`,
  "HOWTO.APPLY.itemTitle_2": `Model Generation`,
  "HOWTO.APPLY.itemContent_2": `Generate a deep learning model based on the acquired images.\nSUALAB provides a basic library of toolkits for performing deep learning model training and tests.`,
  "HOWTO.APPLY.itemTitle_3": `Data Analysis`,
  "HOWTO.APPLY.itemContent_3": `Upon analysis, repeat the model regeneration process in order to achieve the target value around the derived data.`,
  "HOWTO.APPLY.itemTitle_4": `Line Application`,
  "HOWTO.APPLY.itemContent_4": `Apply the completed model to the line.`,
  "HOWTO.APPLY.itemTitle_5": `If you need customized solutions`,
  "HOWTO.APPLY.itemContent_5": `For customers who are unfamiliar with deep learning algorithms, SUALAB operates an Solution Development Department to provide customized model creation and on-site technical support.`,

  "SUPPORT.title": `We appreciate *your inquiries and feedback* regarding SUALAB’s deep learning inspection solutions`,
  "SUPPORT.subTitle": `Product Inquiry`,
  "SUPPORT.name": `Name`,
  "SUPPORT.phone": `Phone Number`,
  "SUPPORT.company": `Company`,
  "SUPPORT.status": `Job Title`,
  "SUPPORT.email": `Email`,
  "SUPPORT.country": `Country`,
  "SUPPORT.reason": `Reason for contacting us`,
  "SUPPORT.reason.item_0": `Please select one`,
  "SUPPORT.reason.item_1": `Product Inquiry`,
  "SUPPORT.reason.item_2": `Partnership`,
  "SUPPORT.reason.item_3": `ETC`,
  "SUPPORT.info": `If you have any questions while using the product,\nPlease send an email to <a href="mailto:support@sualab.com">support@sualab.com</a>`,
  "SUPPORT.vision": `Presence of Vision Inspection Equipment`,
  "SUPPORT.vision.yes": `Yes`,
  "SUPPORT.vision.no": `No`,
  "SUPPORT.vision.dontknow": `Do not know`,
  "SUPPORT.industry": `Industry`,
  "SUPPORT.productType": `Type of Product`,
  "SUPPORT.faultType": `Type of Defect`,
  "SUPPORT.numOfLine": `The Number of Product Lines`,
  "SUPPORT.path": `How did you get the information about SuaKIT?`,
  "SUPPORT.path.item_info": `Please select one`,
  "SUPPORT.path.item_0": `Exhibition / Seminar`,
  "SUPPORT.path.item_1": `Introduction of an acquaintance`,
  "SUPPORT.path.item_2": `Media (Article / Broadcasting, etc)`,
  "SUPPORT.path.item_3": `Search (Portal / Homepage, etc) `,
  "SUPPORT.path.item_4": `ETC`,
  "SUPPORT.supportContent": `Inquiry Details`,
  "SUPPORT.termsAgree": `Agreement on terms on service / collection and use of personal information (Mandatory)`,
  "SUPPORT.adAgree": `Agreement on receiving commercial information (Optional)`,
  "SUPPORT.adAgree.head": `Accept Marketing Information`,
  "SUPPORT.adAgree.content": `If you agree to receive marketing information, you can receive various news related to Sualab products and services.`,
  "SUPPORT.modalBtn": `Read more`,
  "SUPPORT.submitBtn": `SUBMIT`,
  "SUPPORT.modal.ok": `OK`,
  "SUPPORT.alert.success": `We received your inquiry.`,
  "SUPPORT.alert.error": `An error has occurred.`,

  "DOWNLOAD.title": `Experience the upgraded SuaKIT with a *Software Update*`,
  "DOWNLOAD.RELEASE.date": `Release Date`,
  "DOWNLOAD.RELEASE.detail": `Details`,
  "DOWNLOAD.RELEASE.fold": `Fold`,
  "DOWNLOAD.AUTH.companyName": "Company Name",
  "DOWNLOAD.AUTH.companyKey": "Authentication Key",
  "DOWNLOAD.AUTH.authBtn": "Authenticate",
  "DOWNLOAD.AUTH.authFailMessage": "Authentication Failed.\nPlease check your company name and key",
  "DOWNLOAD.SUAKIT.detail": "Details",

  "MEDIA.title": `Check out the *Press Coverage of SUALAB*`,
  "MEDIA.newsDetail.prev": `Previous`,
  "MEDIA.newsDetail.next": `Next`,
  "MEDIA.newsDetail.listBtn": `List`,
  "EVENT.title": `Meet SUALAB through various *events and activities*`,

  "PHILOSOPHY.title": `SUALAB은 *최고의 인재*들이 모여 *즐겁게* 일할 수 있는 조직을 지향합니다`,
  "PHILOSOPHY.title": `SUALAB aims to create an organization where the *best people* can gather and work *happily*`,
  "PHILOSOPHY.FIRST.subTitle": `Philosophy of Personnel`,
  "PHILOSOPHY.FIRST.cardTitle_1": `The Best Colleagues`,
  "PHILOSOPHY.FIRST.cardContent_1": `Working with the best colleagues\nis the best benefit`,
  "PHILOSOPHY.FIRST.cardTitle_2": `Fair Compensation`,
  "PHILOSOPHY.FIRST.cardContent_2": `Fair compensation for\nemployees' efforts`,
  "PHILOSOPHY.FIRST.cardTitle_3": `An Environment for Enjoyable Work`,
  "PHILOSOPHY.FIRST.cardContent_3": `Create a culture and workplace environment conducive to happiness`,
  "PHILOSOPHY.SECOND.subTitle": `Talent`,
  "PHILOSOPHY.SECOND.itemTitle_1": `Problem-Solving Ability`,
  "PHILOSOPHY.SECOND.itemContent_1": `SUALAB seeks to solve problems that others cannot.\n  To do this, one needs a problem-solving ability that allows for flexible and innovative application of a variety of competencies.`,
  "PHILOSOPHY.SECOND.itemTitle_2": `Passion for Growth`,
  "PHILOSOPHY.SECOND.itemContent_2": `The individuals at SUALAB are growth-oriented. We do not neglect our efforts to become the best in our field, and we pursue the value of “growth” with passion.`,
  "PHILOSOPHY.THIRD.subTitle": `Benefits System`,
  "PHILOSOPHY.THIRD.contentItem_1": `Insurance Coverage`,
  "PHILOSOPHY.THIRD.contentItem_2": `Support for attending domestic/international seminars`,
  "PHILOSOPHY.THIRD.contentItem_3": `Selective Benefits`,
  "PHILOSOPHY.THIRD.contentItem_4": `Lunch/dinner and snacks provided`,
  "PHILOSOPHY.THIRD.contentItem_3.infoTitle": `*What are Selective Benefits?`,
  "PHILOSOPHY.THIRD.contentItem_3.infoContent": `This system allows an employee to select certain expenses required for self-development such as educational expenses, book costs, and gym fees`,

  "RECRUIT.title": `We're looking for the *best talent* to join our team`,
  "RECRUIT.LAB.subTitle": `Research Lab`,
  "RECRUIT.LAB.infoTextBox1": `Recruitment of research personnel may vary for each job.\nPlease check the job announcement for details.`,
  "RECRUIT.LAB.infoTextBox2": `The project assignment is a step to verify the required\ncompetency of the job, and the evaluation of this step\nwill determine whether or not the second interview will take place.\n_* The selection process is only applicable for select jobs_`,
  "RECRUIT.LAB.step_1": `Document Review`,
  "RECRUIT.LAB.step_2": `Phone Screening`,
  "RECRUIT.LAB.step_3": `1st Interview`,
  "RECRUIT.LAB.step_4": `Project Assignment`,
  "RECRUIT.LAB.step_5": `2nd Interview`,
  "RECRUIT.LAB.step_6": `Hire Decision`,
  "RECRUIT.MANAGE.subTitle": `Sales and Management`,
  "RECRUIT.MANAGE.step_1": `Document Review`,
  "RECRUIT.MANAGE.step_2": `1st Interview`,
  "RECRUIT.MANAGE.step_3": `2nd Interview`,
  "RECRUIT.MANAGE.step_4": `Hire Decision`,

  "OFFICE.title": `SUALAB is always open for you`,
  "OFFICE.address": `Address`,
  "OFFICE.phone": `Phone`,
  "OFFICE.fax": `Fax`,
  "OFFICE.email": `Email`,
  "OFFICE.question.common": `General Inquiry`,
  "OFFICE.question.sales": `Sales Inquiry`,
  "OFFICE.question.recruit": `Careers`,
  "OFFICE.phone.represent": `Main Phone`,
  "OFFICE.base": `Headquarters`,
  "OFFICE.base.address": `Seoul National University Research Park 511\nGwanak-ro 1, Gwanak-gu, Seoul`,
  "OFFICE.china": `China Office`,

  "NETWORK.title": `SUALAB is expanding throughout the *world* with *global business partners*`,
};
