export default {
  "NAVBAR.product.support": `제품문의`,
  "NAVBAR.career.philosophy": `인사 철학`,
  "NAVBAR.career.recruit": `채용 절차`,

  "FOOTER.sualabInfo": `사업자등록번호 : 220-88-55558 l 일반문의 : 02-6264-0366 | 영업문의 : 02-6264-0362\n대표이사 : 송기영 l 주소 : 서울시 관악구 관악로 1 서울대학교 연구공원 본관 511호\nCopyright ⓒSualab. All Rights Reserved.`,
  "FOOTER.privateTerms": `개인정보처리방침`,

  "MAIN.FIRST.subTitle": `SUALAB은 인공지능을 기반으로 기계 대신 사람이 하던 일을 자동화함으로써\n세상에 기여할 수 있다고 믿습니다.`,
  "MAIN.SECOND.awardContent_1": `2017 Innovators Awards\nPLATINUM 수상`,
  "MAIN.SECOND.awardContent_2": `2017 KGCCI Innovation Awards\n디지털혁신 부문 수상`,
  "MAIN.SECOND.awardContent_3": `2016 AIA VIsion Show\nGlobal Top 8 Start-up`,
  "MAIN.THIRD.bigTitle": `고객사`,
  "MAIN.THIRD.content": `SUALAB은 훌륭한 기술력을 입증 받아\n유수의 대기업들에 다양한 솔루션을 제공하고 있습니다.`,
  "MAIN.FOURTH.bigTitle": `블로그`,
  "MAIN.FOURTH.subTitle": `딥러닝 머신비전, 머신 러닝 등 SUALAB의 기술에 대해 더 자세히 알고 싶다면?`,
  "MAIN.FOURTH.blogBtn": `SUALAB 기술 블로그`,
  "MAIN.FIFTH.bigTitle": `최신 소식`,

  "ABOUT.FIRST.title": `SUALAB은 *머신비전 분야*에 특화된 *딥러닝 검사 솔루션*을 제공하는 글로벌 기업입니다`,
  "ABOUT.SECOND.missionSubContent": `노력에 대한 정당한 보상과 일하는 즐거움을 통해 구성원들을 행복하게 하고,\n사람이 기계 대신 하던 일에서 벗어나도록 하여 세상에 기여합니다.`,
  "ABOUT.SECOND.visionSubContent": `딥러닝 기반 Vision Inspection 분야의 Global No.1`,
  "ABOUT.THIRD.title": `*딥러닝 머신비전 솔루션* 글로벌 리더`,
  "ABOUT.THIRD.content": `SUALAB은 인공지능을 기반으로 한 Deep Learning Machine Vison Solution Provider 입니다.\n\nSUALAB은 컴퓨터, 전자, 기계 분야 등의 우수한 엔지니어들이 모여 각 분야의 기술을 융합하여 인간을 보다 편리하게 하는 다양한 기술과 제품을 연구합니다.\n\n특히, 딥러닝, 머신비전 그리고 슈퍼컴퓨팅 기술을 바탕으로 산업현장에서 인간의 눈을 대신 할 수 있는 다양한 머신 비전 시스템을 연구하여 제조 산업의 정밀 검사를 가능하게 합니다.`,
  "ABOUT.FOURTH.subContent": `SUALAB은 인공지능 이미지 해석 기술을 기반으로, 기존 머신비전 기술로 검사가 어려운\n디스플레이, 태양광, PCB, 필름, 반도체 등의 분야를 위한 무인 검사 자동화 솔루션을 제공합니다.`,
  "ABOUT.FOURTH.itemContent_1": `딥러닝 학습 최적화를 위해 머신비전 알고리즘 등 다양한 기술을 활용하여 이미지 전처리를 수행합니다.`,
  "ABOUT.FOURTH.itemContent_2": `SUALAB이 자체 개발한 학습망과 GPU 컴퓨팅 기술을 활용하여 1000분의 1초 단위의 실시간 분석을 진행합니다.`,
  "ABOUT.FOURTH.itemContent_3": `검사 리포트 생성, 검사 결과 Database화, 불량 지점 마킹 등이 가능한 S/W를 제공합니다.`,

  "PEOPLE.title": `SUALAB은 *최고의 사람들*과 함께 합니다`,
  "PEOPLE.laboratory": `연구소`,
  "PEOPLE.business": `영업 본부`,
  "PEOPLE.manage": `경영관리 본부`,

  "SUAKIT.title": `*딥러닝*을 탑재한 SuaKIT, *머신비전 검사*의 스펙트럼을 넓힙니다`,
  "SUAKIT.FIRST.content": `SuaKIT은 디스플레이, 태양광, PCB, 필름, 반도체 등 다양한 제조업 현장에서 사용할 수 있는 딥러닝 머신비전 검사 소프트웨어입니다.`,
  "SUAKIT.FIRST.cardContent_1": `제조현장에서 발생하는 다양한 불량들을 이미지 분석을 통해 정확한 영역 형태로 검출해냅니다.\n\n다양한 표면 형태를 가지고 있는 태양광 패널,\n카메라 렌즈 등에서 여러 불량 유형을 검출하고,\n이를 유형별로 정리할 수 있습니다.`,
  "SUAKIT.FIRST.cardContent_2": `정의한 Feature/Class에 맞춰\nImage Set을 분류합니다.\n\n다양한 표면 형태를 가지고 있는 태양광 패널, 카메라 렌즈 등에서 여러 불량 영역을 정확히 검출하고\n유형 별로 분류할 수 있습니다.`,
  "SUAKIT.FIRST.cardContent_3": `정의한 Feature/Class에 맞춰 한 이미지 상의\n여러 물체들을 박스 형태로 검출합니다.\n\n기계/부품류 등의 제조 라인에서\n여러 물체가 촬영된 하나의 사진을 분석해\n각각의 물체를 검출해낼 수 있습니다.`,
  "SUAKIT.SECOND.subTitle": `적용 사례`,
  "SUAKIT.SECOND.display": `디스플레이`,
  "SUAKIT.SECOND.conduct": `반도체`,
  "SUAKIT.SECOND.sunlight": `태양광`,
  "SUAKIT.SECOND.film": `필름`,
  "SUAKIT.SECOND.etcContent": `그 외 자동차 부품, 전기/전자 제품 등\n다양한 제조업 현장에서 실제 적용 중입니다.`,
  "SUAKIT.THIRD.subTitle": `기존 머신비전 검사 vs SuaKIT`,
  "SUAKIT.THIRD.subContent": `SuaKIT의 딥러닝 알고리즘을 통해 전통적인 머신비전 검사방식의 한계를 극복할 수 있습니다.`,
  "SUAKIT.THIRD.headItem": `기존 머신비전 검사`,
  "SUAKIT.THIRD.itemTitle_1": `복잡한 이미지 해석 불가`,
  "SUAKIT.THIRD.itemContent_1": `이미지가 불규칙하고 비정형인 경우, 불량의 특징값(Feature)을 수동으로 설정하기 어렵습니다. 따라서 아직 사람의 육안검사에 의존하는 영역이 많습니다.`,
  "SUAKIT.THIRD.itemTitle_2": `딥러닝 기반 고정밀 이미지 해석 가능`,
  "SUAKIT.THIRD.itemContent_2": `SuaKIT은 이미지의 복잡도와 무관하게, 불량의 특징값(Feature)을 딥러닝 알고리즘을 통해 자동으로 학습해 분석할 수 있습니다.`,
  "SUAKIT.THIRD.itemTitle_3": `낮은 정확도`,
  "SUAKIT.THIRD.itemContent_3": `기존 머신비전 검사의 경우, 불량의 특징값(Feature)을 정한 후에는 다음 기준 설정시까지 특징값이 바뀌지않기 때문에, 약간의 변형에도 취약하여 정확도가 낮습니다. 또한, 육안 검사의 경우 사람의 눈에 의존하기때문에 개인마다 다른 기준을 사용하기 쉽습니다.`,
  "SUAKIT.THIRD.itemTitle_4": `높은 정확도`,
  "SUAKIT.THIRD.itemContent_4": `딥러닝 알고리즘의 도입으로 제품의 변화에 유연히 대처할 뿐만 아니라, 제조업 분야의 다양한 납품실적을 기반으로 제조업 특화 알고리즘 및 방법론 등을 활용하여 검사 정확도를 대폭 향상시켰습니다.`,
  "SUAKIT.THIRD.itemTitle_5": `과다한 최적화 비용`,
  "SUAKIT.THIRD.itemContent_5": `제품 종류가 다양하고, 모델 교체가 잦은 경우 매번 최적화를 위한 과다한 프로그래밍 비용이 발생합니다.`,
  "SUAKIT.THIRD.itemTitle_6": `딥러닝 기반 자동 최적화`,
  "SUAKIT.THIRD.itemContent_6": `불량 유형별 사진만 있으면 손쉽게 자동으로 프로그램을 최적화할 수 있을 뿐만 아니라, 라인 적용 후 취득되는
  이미지로 추가 학습이 가능합니다.`,
  "SUAKIT.FOURTH.itemTitle_1": `검사 정확도 향상`,
  "SUAKIT.FOURTH.itemContent_1": `딥러닝 기반 검사 알고리즘을 통해 육안검사, 기존 머신비전 검사보다 높은 검사 정확도를 확보할 수 있습니다.`,
  "SUAKIT.FOURTH.itemTitle_2": `인력 운영 효율화`,
  "SUAKIT.FOURTH.itemContent_2": `높은 정확도 기반으로 자동화 검사를 수행하기 때문에, 한 명의 관리 인력으로도 다수의 검사 장비를 관리할 수 있습니다.`,
  "SUAKIT.FOURTH.itemTitle_3": `최적화 비용 절감`,
  "SUAKIT.FOURTH.itemContent_3": `학습 과정이 빠르고 용이하여 알고리즘 최적화 과정을 손쉽게 단축시킬 수 있으며, 라인 적용 후 취득되는 이미지들로 추가 학습이 가능하여 최적화 비용이 절감됩니다.`,
  "SUAKIT.FOURTH.itemTitle_4": `극대화된 처리 속도`,
  "SUAKIT.FOURTH.itemContent_4": `CUDA, cuDNN 등 GPU 전용 처리언어를 활용하여 딥러닝 알고리즘을 구현하고 Multi-GPU, Multi-Threading 등을 지원해 이미지 처리속도를 극대화 할 수 있습니다.`,
  "SUAKIT.FOURTH.itemTitle_5": `높은 호환성`,
  "SUAKIT.FOURTH.itemContent_5": `C++, C# API 제공을 통해, 기존에 동일언어로 작업된 소프트웨어를 큰 변화없이 검사 알고리즘만 교체하여 사용할 수 있습니다.`,
  "SUAKIT.FOURTH.itemTitle_6": `사용자 친화적 UI`,
  "SUAKIT.FOURTH.itemContent_6": `직관적인 UI를 기반으로 최상의 UX를 제공하여 사용자 편의성을 극대화하였습니다.딥러닝 전문가가 아닌 사람도 라벨링 툴부터 결과 출력까지 모든 검사 과정을 쉽게 진행할 수 있습니다.`,
  "SUAKIT.FIFTH.question_1": `유형별로 몇 장 정도의 이미지 데이터를 학습시켜야 하나요?`,
  "SUAKIT.FIFTH.answer_1": `이미지의 복잡성 정도에 다르지만, 초기에는 불량 유형별 100장 내외를 제공해주시면 됩니다.`,
  "SUAKIT.FIFTH.question_2": `망 학습에 소요되는 시간은 어느 정도 걸리나요?`,
  "SUAKIT.FIFTH.answer_2": `학습시키는 이미지 개수에 따라 다르지만 1024*1024 사이즈, 1,000장 기준으로 20분 내외의 시간이 소요됩니다.`,
  "SUAKIT.FIFTH.question_3": `검사라인에서 이미지 데이터를 처리하는 속도가 어떻게 되나요?`,
  "SUAKIT.FIFTH.answer_3": `Segmentation / Geforce GTX-1080Ti 기준 1024X1024 사이즈 이미지에 대해 실시간으로 초당 20장 내외로 처리가 가능합니다`,
  "SUAKIT.FIFTH.question_4": `SuaKIT 사용에 대한 교육, 혹은 세미나가 진행되나요?`,
  "SUAKIT.FIFTH.answer_4": `제품문의를 주실 경우 직접 방문하여 SuaKIT에 대한 설명 및 사용법을 알려드리며, SuaKIT 대여, 혹은 구매 후 공식적인 Tutorial이 진행됩니다.`,
  "SUAKIT.FIFTH.question_5": `SuaKIT과 기존 검사 알고리즘이 연동 가능한가요? 가능하다면 어떤 방식으로 진행되나요?`,
  "SUAKIT.FIFTH.answer_5": `SuaKIT은 C++, C# API를 제공하고 있습니다. 기존 검사 알고리즘이 C++, C#으로 개발되어 있다면 API를 통해 쉽게 연동할 수 있습니다.`,
  "SUAKIT.FIFTH.question_6": `SuaKIT 데모 버전이 있나요?`,
  "SUAKIT.FIFTH.answer_6": `없습니다. 대신 영업일 기준 20일 동안 SuaKIT을 대여할 수 있으며, 필요시 추가 계약을 통해 1회 연장할 수 있습니다.`,
  "SUAKIT.SIXTH.subTitle": "Suakit 브로셔",

  "HOWTO.title": `*누구나* 손쉽게 *딥러닝 모델을* 생성하고 *제조 현장에 적용*할 수 있습니다`,
  "HOWTO.USAGE.subTitle": `SuaKIT 사용 Process`,
  "HOWTO.USAGE.content": `직관적인 UI의 SuaKIT을 사용하면 누구나 쉽게 딥러닝 모델을 생성하고 테스트 할 수 있습니다.`,
  "HOWTO.USAGE.segmentation.title_1": `01. 이미지 로딩`,
  "HOWTO.USAGE.segmentation.content_1": `학습/테스트할 정상 및 결함 이미지를 불러옵니다.`,
  "HOWTO.USAGE.segmentation.title_2": `02. 이미지 분류`,
  "HOWTO.USAGE.segmentation.content_2": `불러온 이미지들을 학습용/검증용/테스트용 이미지로 분류합니다.`,
  "HOWTO.USAGE.segmentation.title_3": `03. 라벨링`,
  "HOWTO.USAGE.segmentation.content_3": `이미지 상의 결함 부분을 각각의 불량 유형으로 라벨링합니다.`,
  "HOWTO.USAGE.segmentation.title_4": `04. 모델 생성`,
  "HOWTO.USAGE.segmentation.content_4": `라벨링된 이미지들을 분석하여 딥러닝 모델을 생성합니다.`,
  "HOWTO.USAGE.segmentation.title_5": `05. 테스트`,
  "HOWTO.USAGE.segmentation.content_5": `테스트를 통해 딥러닝 모델이 검출한 불량영역을 확인합니다.`,
  "HOWTO.USAGE.segmentation.title_6": `06. 모델 export`,
  "HOWTO.USAGE.segmentation.content_6": `생성된 모델을 export하여 기존 C++/C# 소프트웨어와 연동하여 사용합니다.`,
  "HOWTO.USAGE.classification.content_3": `이미지 상의 결함 부분을 각각의 불량 유형으로 라벨링합니다.`,
  "HOWTO.USAGE.detection.content_3": `이미지 상의 결함 부분을 각각의 불량 유형으로 라벨링합니다.`,
  "HOWTO.USAGE.classification.content_5": `테스트를 통해 유형별로 분류된 이미지들을 확인합니다.`,
  "HOWTO.USAGE.detection.content_5": `테스트를 통해 유형별로 분류된 이미지들을 확인합니다.`,
  "HOWTO.APPLY.subTitle": `SuaKIT 적용 Process`,
  "HOWTO.APPLY.content": `다음과 같은 절차를 통해 SuaKIT을 적용할 수 있습니다.`,
  "HOWTO.APPLY.itemTitle_1": `이미지 취득`,
  "HOWTO.APPLY.itemContent_1": `기존에 설치된 머신 비전 장비를 통해 이미지를 취득합니다.`,
  "HOWTO.APPLY.itemTitle_2": `딥러닝 모델 생성`,
  "HOWTO.APPLY.itemContent_2": `취득한 이미지를 바탕으로 딥러닝 모델을 생성합니다. SUALAB은 딥러닝 모델 학습 및 테스트를 수행할 수 있는 기본 툴킷 라이브러리를 제공합니다.`,
  "HOWTO.APPLY.itemTitle_3": `데이터`,
  "HOWTO.APPLY.itemContent_3": `도출된 데이터를 중심으로 목표 수치를 달성 할 수 있도록 분석 후 모델 재생성 과정을 반복합니다.`,
  "HOWTO.APPLY.itemTitle_4": `라인 적용`,
  "HOWTO.APPLY.itemContent_4": `완성된 모델을 라인에 적용합니다.`,
  "HOWTO.APPLY.itemTitle_5": `맞춤형 솔루션이 필요한 경우`,
  "HOWTO.APPLY.itemContent_5": `딥러닝 알고리즘에 익숙하지 않은 고객을 위해 SUALAB은 응용개발팀을 운영하여 맞춤형 모델 생성,\n현장 기술 지원 등 유형별 솔루션을 제공하고 있습니다.`,

  "SUPPORT.title": `SUALAB의 딥러닝 검사 솔루션에 대한 고객분들의 *문의*를 기다립니다`,
  "SUPPORT.subTitle": `제품 문의`,
  "SUPPORT.name": `이름`,
  "SUPPORT.phone": `전화번호`,
  "SUPPORT.company": `회사`,
  "SUPPORT.status": `직급`,
  "SUPPORT.email": `Email`,
  "SUPPORT.country": `국가`,
  "SUPPORT.reason": `문의이유`,
  "SUPPORT.reason.item_0": `문의 이유를 선택하세요.`,
  "SUPPORT.reason.item_1": `제품 문의`,
  "SUPPORT.reason.item_2": `Partnership`,
  "SUPPORT.reason.item_3": `기타`,
  "SUPPORT.info": `제품 사용 중 생긴 문의 사항은 현재 페이지가 아닌\n<a href="mailto:support@sualab.com">support@sualab.com</a>으로 메일을 보내시길 바랍니다.`,
  "SUPPORT.vision": `Vision 검사 장비 보유 유/무`,
  "SUPPORT.vision.yes": `유`,
  "SUPPORT.vision.no": `무`,
  "SUPPORT.vision.dontknow": `모름`,
  "SUPPORT.industry": `산업`,
  "SUPPORT.productType": `제품 유형`,
  "SUPPORT.faultType": `불량 유형`,
  "SUPPORT.numOfLine": `생산라인 수`,
  "SUPPORT.path": `알게 된 경로`,
  "SUPPORT.path.item_info": `알게 된 경로를 선택하세요`,
  "SUPPORT.path.item_0": `전시회/세미나`,
  "SUPPORT.path.item_1": `주변인 소개`,
  "SUPPORT.path.item_2": `매체(기사/방송 등)`,
  "SUPPORT.path.item_3": `검색(포탈/홈페이지 등) `,
  "SUPPORT.path.item_4": `기타`,
  "SUPPORT.supportContent": `문의 내용`,
  "SUPPORT.termsAgree": `서비스 약관, 개인정보 수집 및 이용 동의 (필수)`,
  "SUPPORT.adAgree": `광고성 정보수신 동의 (선택)`,
  "SUPPORT.adAgree.head": `마케팅 정보수신 동의`,
  "SUPPORT.adAgree.content": `마케팅 정보 수신에 동의하실 경우 수아랩 제품·서비스와 관련된 각종 소식 등을 받으실 수 있습니다.`,
  "SUPPORT.modalBtn": `자세히 보기`,
  "SUPPORT.submitBtn": `문의 제출 하기`,
  "SUPPORT.modal.ok": `확인`,
  "SUPPORT.alert.success": `문의가 접수되었습니다.`,
  "SUPPORT.alert.error": `오류가 발생했습니다.`,

  "MEDIA.title": `*언론*에 보도된 *SUALAB*을 확인해 보세요`,
  "MEDIA.newsDetail.prev": `이전 글`,
  "MEDIA.newsDetail.next": `다음 글`,
  "MEDIA.newsDetail.listBtn": `목록으로 돌아가기`,
  "EVENT.title": `다양한 *행사* 및 *활동*을 통해 SUALAB과 만나보세요`,

  "PHILOSOPHY.title": `SUALAB은 *최고의 인재*들이 모여 *즐겁게* 일할 수 있는 조직을 지향합니다`,
  "PHILOSOPHY.FIRST.subTitle": `인사 철학`,
  "PHILOSOPHY.FIRST.cardTitle_1": `최고의 인재`,
  "PHILOSOPHY.FIRST.cardContent_1": `최고의 동료와 함께\n일하는 것이 최고의 복지`,
  "PHILOSOPHY.FIRST.cardTitle_2": `정당한 보상`,
  "PHILOSOPHY.FIRST.cardContent_2": `구성원들의 노력에 대한\n정당한 보상을 제공`,
  "PHILOSOPHY.FIRST.cardTitle_3": `즐겁게 일할 수 있는 환경`,
  "PHILOSOPHY.FIRST.cardContent_3": `즐겁게 일할 수 있는\n문화와 환경을 조성하겠다는 철학`,
  "PHILOSOPHY.SECOND.subTitle": `인재상`,
  "PHILOSOPHY.SECOND.itemTitle_1": `문제 해결 능력`,
  "PHILOSOPHY.SECOND.itemContent_1": `SUALAB은 남들이 풀지 못하는 문제를 풀고자 합니다.\n 이를 위해서는 마치 공구상자에서 적합한 Tool을 하나둘씩 꺼내어 보듯\n 다양한 역량을 유연하게 적용할 수 있는 문제해결 능력이 필요합니다.`,
  "PHILOSOPHY.SECOND.itemTitle_2": `성장을 위한 열정`,
  "PHILOSOPHY.SECOND.itemContent_2": `SUALAB의 인재들은 성장을 지향합니다.\n자신의 분야에서 최고가 되기 위한 노력을 게을리 하지 않으며,\n열정을 가지고 ‘성장’이라는 가치를 추구합니다.`,
  "PHILOSOPHY.THIRD.subTitle": `복지 제도`,
  "PHILOSOPHY.THIRD.contentItem_1": `4대 보험지원`,
  "PHILOSOPHY.THIRD.contentItem_2": `국내/외 세미나 참석 지원`,
  "PHILOSOPHY.THIRD.contentItem_3": `선택적 복지 제도`,
  "PHILOSOPHY.THIRD.contentItem_4": `중/석식 및 간식 제공`,
  "PHILOSOPHY.THIRD.contentItem_3.infoTitle": `*선택적 복지란?`,
  "PHILOSOPHY.THIRD.contentItem_3.infoContent": `교육비, 도서비, Gym 이용비 등 자기계발에 필요한 비용을 일정 지원금액 내에서 선택하여 사용하는 제도`,

  "RECRUIT.title": `함께 *즐겁게* 일할 *최고의 인재*를 기다립니다`,
  "RECRUIT.LAB.subTitle": `연구소`,
  "RECRUIT.LAB.infoTextBox1": `연구 인력 채용은 각 직무 별로 상이 할 수 있으니,\n자세한 내용은 _채용공고_를 통해 확인 바랍니다.`,
  "RECRUIT.LAB.infoTextBox2": `프로젝트 과제는 직무의 필요한 역량을 검증하기 위한 단계이며,\n평가에 따라 2차 면접 진행 여부가 결정됩니다.\n_*해당 전형은 일부 직무에서만 진행됩니다._`,
  "RECRUIT.LAB.step_1": `서류 심사`,
  "RECRUIT.LAB.step_2": `전화 면접`,
  "RECRUIT.LAB.step_3": `1차 면접`,
  "RECRUIT.LAB.step_4": `프로젝트 과제`,
  "RECRUIT.LAB.step_5": `2차 면접`,
  "RECRUIT.LAB.step_6": `채용 확정`,
  "RECRUIT.MANAGE.subTitle": `영업본부 및 경영관리본부`,
  "RECRUIT.MANAGE.step_1": `서류 심사`,
  "RECRUIT.MANAGE.step_2": `1차 면접`,
  "RECRUIT.MANAGE.step_3": `2차 면접`,
  "RECRUIT.MANAGE.step_4": `채용 확정`,

  "OFFICE.title": `SUALAB은 언제나 여러분을 향해 열려 있습니다`,
  "OFFICE.address": `주소`,
  "OFFICE.phone": `전화`,
  "OFFICE.fax": `팩스`,
  "OFFICE.email": `메일`,
  "OFFICE.question.common": `일반 문의`,
  "OFFICE.question.sales": `영업 문의`,
  "OFFICE.question.recruit": `채용 문의`,
  "OFFICE.phone.represent": `대표 번호`,
  "OFFICE.base": `본사`,
  "OFFICE.base.address": `서울시 관악구 관악로1 서울대학교 연구공원 본관 511호`,
  "OFFICE.china": `중국 법인`,

  "NETWORK.title": `SUALAB은 *비즈니스 파트너*들과 함께 *세계*로 나아가고 있습니다`,
};
