export const ceoList = [
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Song_Kiyoung.jpg",
    name: "송기영",
    engName: "Kiyoung, Song",
    position: "CEO, Co-Founder",
    detail: [
      "인텔코리아 MCG VIED",
      "에스엔유프리시젼 연구팀",
      "서울대학교 기계항공공학부",
      "서울대학교 컴퓨터공학부(부)",
    ],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Yoon_Kwanwoo.jpg",
    name: "윤관우",
    engName: "Kwanwoo, Yoon",
    position: "CTO, Co-Founder",
    detail: ["삼성 에스원 디바이스 개발그룹", "에스엔유프리시젼 연구팀", "한양대학교 기계공학 석사"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Moon_Taeyeon.jpg",
    name: "문태연",
    engName: "Taeyeon, Moon",
    position: "CSO",
    detail: [
      "두산밥캣 오퍼레이션 전략",
      "두산 지주사 전략기획실(Tri-C)",
      "서울대학교 기계항공공학부",
      "서울대학교 경영학과(부)",
    ],
  },
];

export const researchList = [
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kang_Hyeongshin1.jpg",
    name: "강형신",
    engName: "Hyeongshin, Kang",
    position: "Research Engineer",
    detail: ["연세대학교 컴퓨터과학과"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Lee_Donghoe.jpg",
    name: "이동호",
    engName: "Donghoe, Lee",
    position: "Research Engineer",
    detail: ["연세대학교 컴퓨터과학과"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kim_Gwangmin.jpg",
    name: "김광민",
    engName: "Gwangmin, Kim",
    position: "Research Engineer",
    detail: ["가톨릭대학교 정보통신전자공학과"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kim_Kilho.jpg",
    name: "김길호",
    engName: "Kilho, Kim",
    position: "Research Engineer",
    detail: ["서울대학교 산업공학과 석사"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Shin_Yeonsik.jpg",
    name: "신연식",
    engName: "Yeonsik, Shin",
    position: "Research Engineer",
    detail: ["고려대학교 컴퓨터통신공학부", "안랩 소프트웨어 개발실", "해피나믹"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Ki_Hongdo.jpg",
    name: "기홍도",
    engName: "Hongdo, Ki",
    position: "Research Engineer",
    detail: ["서울대학교 산업공학과 석사"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Lee_Namgoo.jpg",
    name: "이남구",
    engName: "Namgoo, Lee",
    position: "Research Engineer",
    detail: ["서울대학교 컴퓨터공학과 석사"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kang_Junghoon.jpg",
    name: "강정훈",
    engName: "Junghoon, Kang",
    position: "Research Engineer",
    detail: ["듀크대 컴퓨터과학부 석사", "버클리대 전기컴퓨터과학부 학사"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Lee_Jaehwan.jpg",
    name: "이재환",
    engName: "Jaehwan, Lee",
    position: "Research Engineer",
    detail: ["삼성전자 서비스 인텔리전스팀", "상명대학교 컴퓨터과학과"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kim_Hyunjun.jpg",
    name: "김현준",
    engName: "Hyunjun, Kim",
    position: "Research Engineer",
    detail: ["서울대학교 전기정보공학과 석사"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Keum_Jongsoo.jpg",
    name: "금종수",
    engName: "Jongsoo, Keum",
    position: "Research Engineer",
    detail: ["광주과학기술원 전기전자컴퓨터공학부 석사"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Park_Jongho.jpg",
    name: "박종호",
    engName: "Jongho, Park",
    position: "Research Engineer",
    detail: ["서울대학교 컴퓨터공학부 석사"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Joo_Mingyu.jpg",
    name: "주민규",
    engName: "Mingyu, Joo",
    position: "Research Engineer",
    detail: ["고려대학교 전기전자공학과 석사", "고려대학교 전기전자공학과"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Baek_Hosik.jpg",
    name: "백호식",
    engName: "Hosik, Baek",
    position: "Research Engineer",
    detail: ["건국대학교 벤처경영공학 석박사(통)", "동국대학교 산업시스템공학과", "기상청 국가기상위성센터 연구팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Park_Jongkwan.jpg",
    name: "박종관",
    engName: "Jongkwan, Park",
    position: "응용개발팀 책임연구원",
    detail: ["한양대학교 전자공학전공", "에스엔유프리시젼 연구팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Choi_Ickhyun.jpg",
    name: "최익현",
    engName: "Ickhyun, Choi",
    position: "MVTF팀 연구원",
    detail: ["인하대학교 전자공학과 석사", "인하대학교 전자공학전공", "고영테크놀러지 Vision팀 LG전자 VC사업부"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Song_Hadeok.jpg",
    name: "송하덕",
    engName: "Hadeok, Song",
    position: "솔루션개발팀 연구원",
    detail: ["명지대학교 정보통신공학 석사"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Cho_Hunmin.jpg",
    name: "조훈민",
    engName: "Hoonmin, Cho",
    position: "MVTF팀 PM",
    detail: ["서울대학교 전기컴퓨터공학부 석사", "고영테크놀러지 머신비전 연구소"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kim_Namhoon.jpg",
    name: "김남훈",
    engName: "Namhoon, Kim",
    position: "솔루션개발팀 연구원",
    detail: ["중앙대학교 경영학부"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Shin_Chanwoo.jpg",
    name: "신찬우",
    engName: "Chanwoo, Shin",
    position: "솔루션개발팀 연구원",
    detail: ["건국대학교 융합인재학부"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kwon_Soonwook.jpg",
    name: "권순욱",
    engName: "Soonwook, Kwon",
    position: "소프트웨어개발팀 책임연구원",
    detail: ["삼성전자 SmartTV 외 다수 프로젝트 참여"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kang_Seungyeun.jpg",
    name: "강승연",
    engName: "Seungyeun, Kang",
    position: "소프트웨어개발팀 선임연구원",
    detail: ["선문대학교 정보통신공학과", "넥스트아이 소프트웨어개발팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Ryu_Deoksang.jpg",
    name: "류덕상",
    engName: "Deoksang, Ryu",
    position: "소프트웨어개발팀 선임연구원",
    detail: ["건양대학교 의공학과", "맥사이언스 소프트웨어개발팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Oh_Yongchul.jpg",
    name: "오용철",
    engName: "yongchul, Oh",
    position: "설계팀장",
    detail: ["에스엔유프리시젼 설계팀", "미래컴퍼니 설계팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Yoo_Seunggyun.jpg",
    name: "유승균",
    engName: "Seunggyun, Yoo",
    position: "설계팀 대리",
    detail: ["선문대학교 신소재공학과", "에스엔유프리시젼 설계팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Na_Jongheon.jpg",
    name: "나종헌",
    engName: "Jongheon, Na",
    position: "기술지원팀 대리",
    detail: ["인천대학교 컴퓨터공학과", "다산뉴텍 개발팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Park_Jihoon.jpg",
    name: "박지훈",
    engName: "Jihoon, Park",
    position: "기술지원팀 대리",
    detail: ["인천대학교 컴퓨터공학과"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Jang_Hyunjin.jpg",
    name: "장현진",
    engName: "Hyunjin, Jang",
    position: "기술지원팀 대리",
    detail: ["인천대학교 컴퓨터공학과"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Song_Junseok.jpg",
    name: "송준석",
    engName: "Junseok, Song",
    position: "기술지원팀 대리",
    detail: ["인천대학교 컴퓨터공학과"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kim_Jeonghoon.jpg",
    name: "김정훈",
    engName: "Jeonghoon, Kim",
    position: "기술지원팀 대리",
    detail: ["전북대학교 정밀기계공학과", "구네보코리아 기술팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kim_Chulhoon.jpg",
    name: "김철훈",
    engName: "Chulhoon, kim",
    position: "기술지원팀 대리",
    detail: ["연성대학교 디지털전자과", "넥스트아이 개발팀"],
  },
];

export const salesList = [
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Lee_Donghee.jpg",
    name: "이동희",
    engName: "Donghee, Lee",
    position: "영업본부 이사",
    detail: ["서울대학교 경영학과", "두산 지주사 전략기획실(Tri-C)"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kim_Wangsoo.jpg",
    name: "김왕수",
    engName: "Wangsoo, Kim",
    position: "영업본부 이사",
    detail: ["서울대학교 심리학과", "삼성물산 화학팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Lee_Hongsuk.jpg",
    name: "이홍석",
    engName: "Hongsuk, Lee",
    position: "영업본부 매니저",
    detail: ["서울대학교 경영학과", "LG디스플레이 전략마케팅그룹"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kim_Minseok.jpg",
    name: "김민석",
    engName: "Minseok, Kim",
    position: "영업본부 매니저",
    detail: ["서울대학교 산업공학과", "현대자동차 R&D 전략팀", "컴투스 퍼블리싱팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Jung_Heejae.jpg",
    name: "정희재",
    engName: "Heejae, Jung",
    position: "영업본부 매니저",
    detail: ["서울대학교 경영학과", "현대자동차 수출기획팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Cho_Yonghoon.jpg",
    name: "조용훈",
    engName: "Yonghoon, Cho",
    position: "영업본부 매니저",
    detail: ["서울대학교 산업인력개발학과"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Kim_Hanjun.jpg",
    name: "김한준",
    engName: "Hanjun, Kim",
    position: "영업본부 매니저",
    detail: ["서울대학교 경영학과", "제일기획 캠페인기획팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Hong_Cheoljin.jpg",
    name: "홍철진",
    engName: "Cheoljin, Hong",
    position: "영업본부 매니저",
    detail: ["한국산업기술대학교 전자공학과", "TDK Korea 기술영업팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Noh_Kwangyong.jpg",
    name: "노광용",
    engName: "Kwangyong, Noh",
    position: "영업본부 매니저",
    detail: ["경기대학교 스포츠경영학 전공", "한국후지제록스 B2B 영업"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Mun_Seonho.jpg",
    name: "문선호",
    engName: "Seonho, Mun",
    position: "영업본부 매니저",
    detail: ["경희대학교 컨벤션경영학과"],
  },
];

export const manageList = [
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Yun_Younghoon.jpg",
    name: "윤영훈",
    engName: "Younghoon, Yun",
    position: "경영관리부 부장",
    detail: [
      "서울대학교 기술경영∙경제∙정책전공 석사",
      "고려대학교 공과대학 산업시스템정보공학과",
      "두산 지주사 전략기획실(Tri-C)",
      "ST Unitas 신사업전략팀",
    ],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Lee_Bora.jpg",
    name: "이보라",
    engName: "Bora, Lee",
    position: "경영관리부 팀장",
    detail: ["숙명여자대학교 문화관광학과", "숙명여자대학교 일본학과(부)", "하이트론시스템즈 해외영업팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Son_Kiho.jpg",
    name: "손기호",
    engName: "Kiho, Son",
    position: "경영관리부 매니저",
    detail: ["고려대학교 사학과", "고려대학교 과학기술학융합학과", "고려대학교 경제학과(부)"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Shin_Solbin.jpg",
    name: "신솔빈",
    engName: "Solbin, Shin",
    position: "경영관리부 매니저",
    detail: ["한신대학교 정보통신학과", "나래회계법인 기장팀", "socar 경영관리팀"],
  },
  {
    imgUrl: "https://d2ivzy5c3eic08.cloudfront.net/companyPage/people/Oh_Seungjin.jpg",
    name: "오승진",
    engName: "Seungjin, Oh",
    position: "경영관리부 매니저",
    detail: ["동원대학교 e비즈니스학과", "한국폴리텍대학 CAD&모델링과"],
  },
];
